version: '3.9'
services:
  web:
    build: .
    command: python manage.py runserver localhost:8000
    ports:
      - 8000:8000
  #   depends_on:
  #     - redis

  # redis:
  #   image: redis:6-alpine

  celery:
    build: ./oilapiservice
    command: selery -A oilapiservice worker --loglevel=info



