# Generated by Django 4.0.6 on 2022-07-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reports",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                ("liquid", models.FloatField(verbose_name="Liquid")),
                ("oil", models.FloatField(verbose_name="Oil")),
                ("water", models.FloatField(verbose_name="Water")),
                ("wct", models.FloatField(verbose_name="wct")),
            ],
        ),
    ]
