# Generated by Django 4.0.6 on 2022-08-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reports",
            options={"ordering": ["date"]},
        ),
        migrations.AddField(
            model_name="reports",
            name="task_id",
            field=models.CharField(max_length=36, null=True, verbose_name="Task ID"),
        ),
    ]
