# Generated by Django 4.0.6 on 2022-08-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_alter_reports_options_reports_task_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tasks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True, verbose_name="Date")),
                (
                    "task",
                    models.CharField(max_length=36, null=True, verbose_name="Task ID"),
                ),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.AlterModelOptions(
            name="reports",
            options={},
        ),
    ]
