# Generated by Django 4.0.6 on 2022-08-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0005_tasks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reports",
            name="task_date",
            field=models.DateField(auto_now_add=True, verbose_name="Date of raw creation"),
        ),
    ]
