# Generated by Django 4.0.6 on 2022-08-02 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_reports_task_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reports',
            name='task_id',
        ),
    ]
