# Generated by Django 4.0.6 on 2022-08-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_alter_reports_task_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='date_fin',
            field=models.DateField(default=None, verbose_name='nput date of finish'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='date_start',
            field=models.DateField(default=None, verbose_name='Input date of start'),
        ),
    ]
