# Generated by Django 4.0.6 on 2022-08-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0012_alter_reports_date_fin_alter_reports_date_start"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reports",
            name="date",
            field=models.CharField(max_length=10000, null=True, verbose_name="Date"),
        ),
        migrations.AlterField(
            model_name="reports",
            name="date_fin",
            field=models.DateField(null=True, verbose_name="nput date of finish"),
        ),
        migrations.AlterField(
            model_name="reports",
            name="date_start",
            field=models.DateField(null=True, verbose_name="Input date of start"),
        ),
        migrations.AlterField(
            model_name="reports",
            name="lag",
            field=models.IntegerField(null=True, verbose_name="Lag"),
        ),
        migrations.AlterField(
            model_name="reports",
            name="liquid",
            field=models.CharField(max_length=10000, null=True, verbose_name="Liquid"),
        ),
        migrations.AlterField(
            model_name="reports",
            name="oil",
            field=models.CharField(max_length=10000, null=True, verbose_name="Oil"),
        ),
        migrations.AlterField(
            model_name="reports",
            name="task_id",
            field=models.CharField(max_length=36, null=True, verbose_name="Task ID"),
        ),
        migrations.AlterField(
            model_name="reports",
            name="wct",
            field=models.CharField(max_length=10000, null=True, verbose_name="wct"),
        ),
    ]
