# Generated by Django 4.0.6 on 2022-08-07 13:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0017_calculation_cid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calculation",
            name="task",
        ),
        migrations.AddField(
            model_name="calculation",
            name="task_created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Date of task creation",
            ),
            preserve_default=False,
        ),
    ]
